### PR TITLE
re-add W.R. Young

### PR DESCRIPTION
**Pull request by pdebuyl**

### CODE REVIEW

**Comment by pdebuyl** [comment]
Can you check the ORCID etc of W.R. Young?

**Comment by CoraliePicoche** [comment]
I realize I only used the metadata.tex file when compiling the document, which is now misleading. I apologize for that. In addition to the inclusion of W.R. Young, we (F. Barraquand and I) also need to modify our adress: the second one, "Integrative and Theoretical Ecology, LabEx COTE, University of Bordeaux, Pessac, France" is no longer used. 
Can I modify the .yaml file myself to avoid any further confusion?

**Comment by pdebuyl** [comment]
Indeed, please fix the metadata.yaml file as necessary.

**Comment by CoraliePicoche** [comment]
I have made the necessary changes to the metadata.

**Pull request closed without merging**
